# pandas RIDE financial analysis

In [16]:
import re
import numpy as np
import scipy as sc
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Modify the following code to read the RI 2016 Uniform Charter of Accounts data from the Rhode Island Department of Education Consolidated District Financial Database

See:

http://www.ride.ri.gov/FundingFinance/SchoolDistrictFinancialData/UniformChartofAccounts.aspx#18211078-statewide-consolidated-district-financial-databases

Call the dataframe:  uca

In [17]:
epa = pd.read_csv("../epa.csv")
print(epa.shape)
epa.head()

(2884, 50)

,yr,mfr,mfr name,bidx,vid,cfg,carline,car/truck,cid,police,...,target-a,target-b,target-c,set-a,set-b,set-c,engine code,eng family,vpc,cstdwn
0,2009,20,Chrysler LLC,1,L8JCD8152,0,JOURNEY 2WD,T,215,N,...,37.74,0.6338,0.02404,13.53,0.1037,0.02585,FA-100,9CRXJ04.0TN0,6,16.12
1,2009,20,Chrysler LLC,1,L8JCD8152,0,JOURNEY 2WD,T,215,N,...,37.74,0.6338,0.02404,13.53,0.1037,0.02585,FA-100,9CRXJ04.0TN0,6,16.12
2,2009,20,Chrysler LLC,3,L8JCD8152,1,JOURNEY 4WD,T,215,N,...,37.74,0.6338,0.02404,13.53,0.1037,0.02585,FA-200,9CRXJ04.0TN0,6,16.12
3,2009,20,Chrysler LLC,3,L8JCD8152,1,JOURNEY 4WD,T,215,N,...,37.74,0.6338,0.02404,13.53,0.1037,0.02585,FA-200,9CRXJ04.0TN0,6,16.12
4,2009,20,Chrysler LLC,4,L7JSC0243,2,JOURNEY 2WD,T,144,N,...,27.99,0.5576,0.02097,10.83,0.1288,0.01811,AA-100,9CRXV02.4UP0,4,17.45

## Modify the following code to group field counts by district

In [18]:
epa.groupby(epa['mfr name']).count()

,yr,mfr,bidx,vid,cfg,carline,car/truck,cid,police,rhp,...,target-a,target-b,target-c,set-a,set-b,set-c,engine code,eng family,vpc,cstdwn
mfr name,,,,,,,,,,,,,,,,,,,,,
ASTON MARTIN,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,0
AUDI,192,192,192,192,192,192,192,192,192,192,...,122,122,122,122,122,122,192,192,192,0
BENTLEY MOTORS LTD.,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,0
BMW,137,137,137,137,137,137,137,137,137,137,...,137,137,137,137,137,137,137,137,137,0
Chrysler LLC,133,133,133,133,133,133,133,133,133,133,...,133,133,133,133,133,133,133,133,133,84
FERRARI,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,0
FUJI HEAVY IND,73,73,73,73,73,73,73,73,73,73,...,73,73,73,73,73,73,73,73,73,73
Ford Motor Company,349,349,349,349,349,349,349,349,349,349,...,349,349,349,349,349,349,349,349,349,349
GENERAL MOTORS,428,428,428,428,428,428,428,428,428,428,...,428,428,428,428,428,428,428,428,428,428
GM Daewoo Auto and Technology Company,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
HONDA,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,0
HYUNDAI,60,60,60,60,60,60,60,60,60,60,...,60,60,60,60,60,60,60,60,60,60
JAGUAR CARS LIMITED,28,28,28,28,28,28,28,28,28,28,...,28,28,28,28,28,28,28,28,28,26
KIA MOTORS CORPORATION,67,67,67,67,67,67,67,67,67,67,...,67,67,67,67,67,67,67,67,67,67
LAMBORGHINI,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,0
LAND ROVER,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,0
MASERATI,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,0
MAZDA MOTOR CORP.,83,83,83,83,83,83,83,83,83,83,...,83,83,83,83,83,83,83,83,83,8
MERCEDES BENZ,120,120,120,120,120,120,120,120,120,120,...,120,120,120,120,120,120,120,120,120,120
Mitsubishi Motors Corporation,39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,39,39,39,39,37
Mitsubishi Motors North America,45,45,45,45,45,45,45,45,45,45,...,45,45,45,45,45,45,45,45,45,45
NEW UNITED MOTOR MFG INC,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,0
Nissan,411,411,411,411,411,411,411,411,411,411,...,411,411,411,411,411,411,411,411,411,203
PORSCHE,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,52
"Rolls-Royce Motor Cars, Ltd.",4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,0
"Roush Industries, Inc.",4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
SALEEN PERFORMANCE INC.,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
SUZUKI MOTOR CORPORATION,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
Spyker Automobielen BV,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
TOYOTA,260,260,260,260,260,260,260,260,260,260,...,260,260,260,260,260,260,260,260,260,0
VOLKSWAGEN,120,120,120,120,120,120,120,120,120,120,...,88,88,88,88,88,88,120,120,120,82
VOLVO,67,67,67,67,67,67,67,67,67,67,...,67,67,67,67,67,67,67,67,67,67

## Use the dir() function  to display the attributes and member functions of the dataframe class

In [19]:
#

## Print a list of the column names in dataframe uca

In [20]:
#

## Use the groupby() function to list budget totals by district

In [21]:
#

## Create a new column in uca called 'variance'.  Define it as budget-actual.

In [22]:
#

## use groupby to compute the total variance by district

In [23]:
#